### ISSUE TITLE
chore: consider moving clog to it's own organisation

### ISSUE THREAD

**Issue by PascalPrecht** [clog-tool/clog#65]
Clog repositories are piling up in the thoughtram organisation, which is not a deal breaker, but it might be nicer to have an organisation for that project. We currently have repos for the cli tool (maybe even the library get's it's own repo in the future? @kbknapp), the website, logo media and so on and so forth. We might even end up with corresponding server repositories.

What do you think?

**Comment by kbknapp** [comment]
Originally I preferred keeping the lib and binary in the same repo, but I think the scope of clog has grown enough that I'm now beginning to think splitting the two would have some benefits. 

As for clog getting it's own organization that's not a bad idea. I think clog still small enough that it doesn't *need* it's own organization, but being able to create and split off all the clog related repos in one place would also be really nice ;) All things being equal, I'd vote :+1:

**Comment by PascalPrecht** [comment]
Alrighty, the org has been created and @kbknapp and @cburgdorf are invited as member. You can find it here: https://github.com/clog-tool

When do we want to move the repositories over?

**Comment by cburgdorf** [comment]
I'm happy to move them over if you like. As far as I think it's pretty uncritical since we don't have a running website yet.

**Comment by PascalPrecht** [comment]
Cool, go ahead and feel free to close this issue once done :)

**Comment by PascalPrecht** [comment]
Okay, I moved clog to this org. Closing this issue

**Comment by kbknapp** [comment]
I'm re-opening this for a short period, because I contacted Github requesting the https://github.com/clog user be "reset" due to inactivity so that we could take ownership of it. It hasn't been used since Apr 2013 and was *very* seldom used prior.

Once we receive an official answer from them I'll re-close this issue :wink:

**Comment by kbknapp** [comment]
The Github staff replied and said the `clog` account isn't actually dormant, all activity has been taking place in private. 

I'm re-closing this issue.

**Comment by cburgdorf** [comment]
Ah too bad :-/
