### ISSUE TITLE
Let me publish to npm?

### ISSUE THREAD

**Issue by kentcdodds** [clog-tool/clog#71]
Do you mind if I publish the binary to npm? Unless you have some auto-update magic going on that I'm not aware of, it would make getting updates easier (I'd be happy to keep the module updated). I did this with [cloc](http://npm.im/cloc) (coincidentally a similar name) and it's been handy to be able to simply install it globally using the same package manager that I'm used to. I think it would help adoption as well.

Let me know what you think.

**Comment by kentcdodds** [comment]
Note, if you like the idea, you can feel free to publish it yourself :+1: I just want to get it up there. I don't really care how.

**Comment by cburgdorf** [comment]
Hey Kent, feel free to publish it on npm :+1:

**Comment by kentcdodds** [comment]
Almost got it. I think for this first version I'll only be able to distribute the Mac version... I'm not sure how to have multiple binaries that are platform dependant and [the docs](https://docs.npmjs.com/files/package.json#bin) don't mention anything...

**Comment by kbknapp** [comment]
@kentcdodds each release I've been throwing up a binary on a VPS I've got. Usually I do 64bit OS X, Linux, and Windows builds. There have some pretty major improvements since 0.8.2. Once @cburgdorf puts out a new release I'll rebuild all three binaries and throw them up there. Feel free to grab them!

The binaries are located at: http://wod.twentyfives.net/bin/clog/

**Comment by kentcdodds** [comment]
Is there any way I can subscribe to new versions so I know when to update the npm module?

**Comment by kbknapp** [comment]
At present, the best way would be to "watch" this repo for new releases. But admittedly that comes with some extra noise because you'd get updates on everything that happens to this repo. 

I don't see why we couldn't set up some sort of RSS type feed for new releases and news? (cc @cburgdorf  @PascalPrecht )

**Comment by PascalPrecht** [comment]
I think GitHub already provides such a feature. How's that related to npm?

**Comment by kentcdodds** [comment]
Oh really? I'll look into that.

Alrighty, [npm-clog](http://npm.im/npm-clog) is a thing (can you believe `clog` was taken 😿).

```
~/Developer/clog (master)
👾  $ npm install -g npm-clog
/usr/local/bin/clog -> /usr/local/lib/node_modules/npm-clog/lib/clog
npm-clog@1.0.0 /usr/local/lib/node_modules/npm-clog
~/Developer/clog (master)
👾  $ clog --help
clog v0.7.0
a conventional changelog for the rest of us

USAGE:
	clog [FLAGS] [OPTIONS]

FLAGS:
        --from-latest-tag    use latest tag as start (instead of --from)
    -h, --help               Prints help information
        --major              Increment major version by one (Sets minor and patch to 0)
        --minor              Increment minor version by one (Sets patch to 0)
        --patch              Increment patch version by one
    -v, --version            Prints version information

OPTIONS:
        --from <from>                    e.g. 12a8546
    -o, --outfile <outfile>              Where to write the changelog (Defaults to 'changelog.md')
    -r, --repository <repository>        e.g. https://github.com/thoughtram/clog
        --link-style <style>             The style of repository link to generate, defaults to github [values: Github, Gitlab, Stash]
        --subtitle <subtitle>            e.g. crazy-release-title
        --to <to>                        e.g. 8057684 (Defaults to HEAD when omitted)
        --setversion <ver>               e.g. 1.0.1
~/Developer/clog (master)
👾  $ which clog
/usr/local/bin/clog
```

**Comment by kentcdodds** [comment]
And of course, the changelog is clogged :-) https://github.com/kentcdodds/npm-clog/blob/master/CHANGELOG.md

**Comment by cburgdorf** [comment]
haha, super cool :+1:

**Comment by PascalPrecht** [comment]
@kentcdodds thanks kent! Hey can we maybe at least publish it as `clog-cli` ?

**Comment by kentcdodds** [comment]
Good idea! I'll deprecate the other one and republish!

FYI, using [blogtrottr](https://blogtrottr.com) to subscribe to the [rss feed](https://github.com/clog-tool/clog/releases.atom)

**Comment by PascalPrecht** [comment]
Thanks Kent! :heart:

**Comment by kentcdodds** [comment]
:hand: high five!

```
~/Developer/clog (master)
⛄  $ npm publish
+ clog-cli@1.0.0
~/Developer/clog (master)
⛄  $ npm deprecate npm-clog 'Name changed to clog-cli'
~/Developer/clog (master)
⛄  $ npm install npm-clog
npm WARN deprecated npm-clog@1.0.0: Name changed to clog-cli
npm-clog@1.0.0 node_modules/npm-clog
~/Developer/clog (master)
⛄  $ ..
~/Developer
⛄  $ npm uninstall -g npm-clog
unbuild npm-clog@1.0.0
~/Developer
⛄  $ npm install -g clog-cli
/usr/local/bin/clog -> /usr/local/lib/node_modules/clog-cli/lib/clog
clog-cli@1.0.0 /usr/local/lib/node_modules/clog-cli
~/Developer
⛄  $ clog --help
clog v0.7.0
a conventional changelog for the rest of us

USAGE:
	clog [FLAGS] [OPTIONS]

FLAGS:
        --from-latest-tag    use latest tag as start (instead of --from)
    -h, --help               Prints help information
        --major              Increment major version by one (Sets minor and patch to 0)
        --minor              Increment minor version by one (Sets patch to 0)
        --patch              Increment patch version by one
    -v, --version            Prints version information

OPTIONS:
        --from <from>                    e.g. 12a8546
    -o, --outfile <outfile>              Where to write the changelog (Defaults to 'changelog.md')
    -r, --repository <repository>        e.g. https://github.com/thoughtram/clog
        --link-style <style>             The style of repository link to generate, defaults to github [values: Github, Gitlab, Stash]
        --subtitle <subtitle>            e.g. crazy-release-title
        --to <to>                        e.g. 8057684 (Defaults to HEAD when omitted)
        --setversion <ver>               e.g. 1.0.1
```

Going to wait a few hours before tweeting this so the west coast can wake up and smell the `clog` :-)

**Comment by PascalPrecht** [comment]
Feel free to share it! We do work on a nice website and make an official 1.0 announcement in a couple of day tho :)
